version: "3.8"

services:
  #############################################################################################
  ###                                 TrafficCourt BACKEND                                  ###
  #############################################################################################

  #############################################################################################
  ### Citizen API                                                                           ###
  #############################################################################################
  citizen-api:
    container_name: citizen-api
    build:
      context: ./src/backend/TrafficCourts
      dockerfile: ./Citizen.Service/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: http://*:8080
      FORMRECOGNIZER__APIKEY: ${FORMRECOGNIZER__APIKEY:-}
      FORMRECOGNIZER__ENDPOINT: ${FORMRECOGNIZER__ENDPOINT:-}
      FORMRECOGNIZER__MODELID: ${FORMRECOGNIZER__MODELID:-}
      MASSTRANSIT__TRANSPORT: ${MASSTRANSIT__TRANSPORT:-InMemory}
      RABBITMQ__HOST: rabbitmq
      RABBITMQ__PORT: 5672
      RABBITMQ__USERNAME: ${RABBITMQ__USERNAME:-guest}
      RABBITMQ__PASSWORD: ${RABBITMQ__PASSWORD:-guest}
      REDIS__CONNECTIONSTRING: ${REDIS_CONNECTIONSTRING:-redis:6379,password=password}
      TICKETSEARCHCLIENT__ADDRESS: ${TICKETSEARCHCLIENT__ADDRESS:-http://ticket-search:8080/}
    ports:
      - "5000:8080"
    restart: always
    depends_on: [rabbitmq, ticket-search, redis]
    volumes:
      # mount the current users usersecrets folder
      - "${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro"

  #############################################################################################
  ### Citizen API                                                                           ###
  #############################################################################################
  staff-api:
    container_name: staff-api
    build:
      context: ./src/backend/TrafficCourts
      dockerfile: ./Staff.Service/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: http://*:8080
    ports:
      - "5005:8080"
    restart: always
    depends_on:
      - oracle-data-api    
  
  #############################################################################################
  ### Ticket Search API                                                                     ###
  #############################################################################################
  ticket-search:
    container_name: ticket-search
    build:
      context: ./src/backend/TrafficCourts
      dockerfile: ./TrafficCourts.Ticket.Search.Service/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: http://*:8080
      TICKETSEARCH__SEARCHTYPE: ${TICKETSEARCH__SEARCHTYPE:-Mock}
    ports:
      - "5100:8080"
      - "5110:8088"
    restart: always
    volumes:
      # mount the current users usersecrets folder
      - "${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro"

  #############################################################################################
  ###                           Oracle Data API                                             ###
  #############################################################################################
  oracle-data-api:
    container_name: oracle-data-api
    build:
      context: ./src/backend/oracle-data-api
      args:
        - SKIP_TESTS=true
        - SPLUNK_URL=${SPLUNK_URL:-http://splunk:8088}
        - SPLUNK_TOKEN=${SPLUNK_HEC_TOKEN:-token}
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_PASSWORD=password
        - CODETABLE_REFRESH_ENABLED=${CODETABLE_REFRESH_ENABLED:-true}
        - CODETABLE_REFRESH_CRON=${CODETABLE_REFRESH_CRON:-0 * * * * *}
        - JAVA_OPTS=${JAVA_OPTS:--Dlogging.level.ca.bc.gov.open.jag.tco.oracledataapi=DEBUG}
    depends_on:
      - redis
    ports:
      - "5010:8080"

  #############################################################################################
  ###                                 TrafficCourt FRONTEND                                 ###
  #############################################################################################
  citizen-portal:
    container_name: citizen-portal
    build:
      context: ./src/frontend/citizen-portal
      args:
        - API_BASE_PATH=${API_BASE_PATH:-http://citizen-api:8080/api/}
    restart: always
    ports:
      - "8080:8080"
    ## following is used for testing nginx.conf locally. No need to build the citizen-portal every
    ## time we change the nginx.conf, start a shell in the container and run 'service nginx reload' or '/etc/init.d/nginx reload'
    #volumes:
    #  - ./src/frontend/citizen-portal/nginx.conf:/opt/app-root/etc/nginx.default.d/default.conf
    depends_on: [citizen-api]

  #############################################################################################
  ###                                 TrafficCourt Staff FRONTEND                           ###
  #############################################################################################
  staff-portal:
    container_name: staff-portal
    build:
      context: ./src/frontend/staff-portal
      args:
        - API_BASE_PATH=${API_BASE_PATH:-http://citizen-api:8080/api/}
    restart: always
    ports:
      - "8081:8080"
    depends_on: [citizen-api]
    
  #############################################################################################
  ###                           RABBITMQ                                                    ###
  #############################################################################################
  rabbitmq:
    image: rabbitmq:3.9.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - data-rabbit:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    restart: always

  #############################################################################################
  ###                           Minio                                                       ###
  #############################################################################################
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - type: bind
        source: ./tools/minio
        target: /data
    environment:
      MINIO_ROOT_USER: "username" 
      MINIO_ROOT_PASSWORD: "password"
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set dockerminio http://minio:9000 username password;
      /usr/bin/mc mb dockerminio/traffic-ticket-dev;
      /usr/bin/mc policy set public dockerminio/traffic-ticket-dev;
      exit 0;
      "

  #############################################################################################
  ###                                 REDIS server and UI                                   ###
  #############################################################################################
  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=password
    ports:
      - 6379:6379
      
  redis-ui:
    container_name: redis-ui
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    depends_on:
      - redis
    ports:
      - 8082:8081

volumes:
  data-rabbit:
  data-redis:
