/**
 * Traffic Court Online Citizen Api
 * An API for creating violation ticket disputes
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Point } from './point.model';


/**
 * A list of 4 points representing the quadrilateral bounding box that   outlines the text. The points are listed in clockwise order relative   to the text orientation: top-left, top-right, bottom-right, bottom-left.
 */
export interface BoundingBox { 
    points?: Array<Point> | null;
}

