/**
 * Traffic Court Online Citizen Api
 * An API for creating violation ticket disputes
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DayOfWeek = 'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday';

export const DayOfWeek = {
    Sunday: 'Sunday' as DayOfWeek,
    Monday: 'Monday' as DayOfWeek,
    Tuesday: 'Tuesday' as DayOfWeek,
    Wednesday: 'Wednesday' as DayOfWeek,
    Thursday: 'Thursday' as DayOfWeek,
    Friday: 'Friday' as DayOfWeek,
    Saturday: 'Saturday' as DayOfWeek
};

